package me.coonect.coonect.mock;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import me.coonect.coonect.member.application.domain.model.Member;
import me.coonect.coonect.member.application.port.out.MemberRepository;

public class FakeMemberRepository implements MemberRepository {

  private List<Member> data = new ArrayList<>();
  private Long autoGeneratedId = 0L;

  @Override
  public boolean existsByEmail(String email) {
    return data.stream().anyMatch(member -> member.getEmail().equals(email));
  }

  @Override
  public boolean existsByNickname(String nickname) {
    return data.stream().anyMatch(member -> member.getNickname().equals(nickname));
  }

  @Override
  public Member save(Member member) {
    Long id = member.getId();
    if (id == null || id == 0) {
      Member newMember = Member.withEncodedPassword(++autoGeneratedId,
          member.getEmail(),
          member.getEncodedPassword(),
          member.getNickname(),
          member.getName(),
          member.getBirthday());
      data.add(newMember);
      return newMember;
    }

    data.removeIf(item -> Objects.equals(item.getId(), member.getId()));
    data.add(member);
    return member;
  }
}
